name: jaguar_example_session_models
description: Models for examples demonstrating sessions and authentication using Jaguar.
version: 2.1.6
homepage: https://github.com/Jaguar-dart/session
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar_serializer: ^2.2.0
  jaguar: ^2.1.37
  jaguar_auth: ^2.1.10
  jaguar_common: ^2.1.4

dev_dependencies:
  test: ^1.3.0
  build_runner: ^0.10.0
  jaguar_serializer_cli: ^2.2.0
