name: jaguar_session_jwt
description: JWT session managers for Jaguar to build stateless cross-server sessions based on JWT standard.
version: 2.2.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/session

documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  jaguar: ^2.2.4
  jaguar_jwt: ^2.1.4

dev_dependencies:
  test: ^1.3.0
  jaguar_example_session_models:
    path: ../example_models
  http: ^0.11.3
  jaguar_resty: ^2.6.2
  jaguar_auth: ^2.1.12
  jaguar_common: ^2.1.4
  jaguar_reflect: ^2.2.0