name: jaguar_jwt
description: Provides JWT utilities for Dart including issuing a token, verifing a token and parsing a token.
version: 2.1.6
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/session


environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  auth_header: ^2.1.1
  crypto: ^2.0.5
  rsa_pkcs: ^1.1.4

dev_dependencies:
  test: ^1.3.0
